# A basic pod manifest with labels.
apiVersion: v1
kind: Pod
metadata:
    name: kubia-manual-v2
    labels:
        creation_method: manual
        env: prod
spec:
    containers:
    - image: goku321/go-handler:v1.0
      name: kubia
      ports:
      - containerPort: 8081
        protocol: TCP
